### ISSUE TITLE
Questions from infoq

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/porter#118]
Here are the questions raised by infoq.com

- What are the considerations you had while choosing GoBGP compared to other similar BGP daemons like OpenBGPD?
- Do you have plans for supporting IPv6 addresses in Porter in the future? What challenges do you foresee?
- MetalLB - a similar project - supports a few cloud platforms. It does not support most because those platforms don’t give access to network layers that are required for it to function. Can Porter run on self-managed clouds like OpenStack?
- What kind of monitoring and metrics are available for Porter? Are they Prometheus compatible?

Feel free to leave your comments.

**Comment by duanjiong** [comment]
1. GoBGP is implemented in the go language , easy to integrate , follow-up porter can also support a variety of daemon that implementations the BGP protocol
2. Yes, IPv6 will also be supported, it's not technically difficult at the moment, it's just that many environments are still ipv4, so it's not that urgent.
3. Porter was designed to support load balancing in a physical environment, and you can use this [cloud-controller-manager](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md#load-balancer) for load balancing on IAAS such as openstack.
