### ISSUE TITLE
Failed to deloy Porter chart on KubeSphere

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/porter#120]
How to reproduce:

1. Import an App repo:  https://charts.kubesphere.io/test 

![image](https://user-images.githubusercontent.com/40452856/88779209-14213980-d1bc-11ea-8f38-db1d18943599.png)

2. Deploy Porter from App Template in a `demo` project.

![image](https://user-images.githubusercontent.com/40452856/88779820-c6590100-d1bc-11ea-8301-9e4908d8d1f2.png)

3. Inspect the app status, it shows `pending`.

![image](https://user-images.githubusercontent.com/40452856/88779134-f9e75b80-d1bb-11ea-96f0-4ff1dccde329.png)

4. The related resources are empty.

![image](https://user-images.githubusercontent.com/40452856/88779920-e12b7580-d1bc-11ea-9f96-c887f77f8343.png)

> I have tried for two times, at first I modified the default namespace `porter-system` to `demo`, then I just leave it as `porter-system`, both are pending.

![image](https://user-images.githubusercontent.com/40452856/88780302-5e56ea80-d1bd-11ea-9f75-e52278035ee8.png)

**Comment by FeynmanZhou** [comment]
@zheng1 Any updates on this issue?

**Comment by zheng1** [comment]
@FeynmanZhou  Please try this package https://charts.kubesphere.io/test/porter-0.1.2.tgz

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou Please try this package https://charts.kubesphere.io/test/porter-0.1.2.tgz

okay, let me test it and give feedback later

**Comment by FeynmanZhou** [comment]
verified
