### ISSUE TITLE
与kube-router 50051端口冲突

### ISSUE THREAD

**Issue by laixiaohuai** [kubesphere/porter#135]
你好，现在我用Porter的时候，与kube-router 50051端口冲突了，请问可以把Porter的50051端口修改为其他端口吗？

**Comment by duanjiong** [comment]
You modify the porter-manager deployment yaml with args --api-hosts=":50052" or something like that, and we have the porter chart package under review, which you can also install later with the chart package, which is more convenient.

The link below is to the chart package
https://github.com/kubesphere/helm-charts/pull/118

**Comment by laixiaohuai** [comment]
0.3可以用于Kubernetes 1.14.4吗？我看文档现在标识是最低1.17版本以后，还有，现在porter可以用于生产吧？

**Comment by duanjiong** [comment]
> 0.3可以用于Kubernetes 1.14.4吗？我看文档现在标识是最低1.17版本以后，还有，现在porter可以用于生产吧？

We recommend using the new release, which is more fully tested and ready for production. The specific adaptation of 1.14 can be verified by yourself. Since the k8s is iterating faster, we give priority to the higher version during the development process, and you can give feedback in advance if you have any problem in the process.

I've looked around, and the api used hasn't changed much, so there shouldn't be too much of a problem adapting it.

**Comment by laixiaohuai** [comment]
![image](https://user-images.githubusercontent.com/14883388/100584408-0a087680-3327-11eb-847d-3fbea22b4588.png)
porter manager port is 17900
porter manager global.config already set using-port-forward=true
but my switch(H3C) BGP not support change 179
Now how would I do that?

**Comment by duanjiong** [comment]
You can try the following command on the node where the porter manager is located, and replace the relevant IP in the command

iptables -t nat -A PREROUTING -s ${SWITCH_IP} -p tcp --dport 179 -j DNAT --to-destination ${MANAGER_POD_IP}:17900

**Comment by duanjiong** [comment]
> ![image](https://user-images.githubusercontent.com/14883388/100584408-0a087680-3327-11eb-847d-3fbea22b4588.png)
> porter manager port is 17900
> porter manager global.config already set using-port-forward=true
> but my switch(H3C) BGP not support change 179
> Now how would I do that?

You are using the wrong version, please install with the latest link!
I removed the using-port-forward configuration in the latest version.

https://github.com/kubesphere/porter/blob/master/doc/deploy.md

**Comment by laixiaohuai** [comment]
> > ![image](https://user-images.githubusercontent.com/14883388/100584408-0a087680-3327-11eb-847d-3fbea22b4588.png)
> > porter manager port is 17900
> > porter manager global.config already set using-port-forward=true
> > but my switch(H3C) BGP not support change 179
> > Now how would I do that?
> 
> You are using the wrong version, please install with the latest link!
> I removed the using-port-forward configuration in the latest version.
> 
> https://github.com/kubesphere/porter/blob/master/doc/deploy.md

你好。0.3.1 agent不能起来！
agent log 报错信息：
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by duanjiong** [comment]
Go to the Chinese forum to discuss, before you discuss, you better install a clean environment with the latest links!

**Comment by willzhang** [comment]
latest links is master branch? i have the same agent error:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

my proterlb version v0.3.1

```
https://raw.githubusercontent.com/kubesphere/porter/v0.3.1/deploy/porter.yaml

```

**Comment by duanjiong** [comment]
> latest links is master branch? i have the same agent error:
> 
> ```
> standard_init_linux.go:211: exec user process caused "exec format error"
> ```
> 
> my proterlb version v0.3.1
> 
> ```
> https://raw.githubusercontent.com/kubesphere/porter/v0.3.1/deploy/porter.yaml
> ```

0.3.1 is deprecated, please remove all 0.3.1 components and install with the latest master branch documentation.
