### ISSUE TITLE
The priority of the router ID automatically selected in BgpConf.

### ISSUE THREAD

**Issue by caffeinism** [kubesphere/porter#166]
The document says:
```
routerID: Local router ID, which is usually set to the IP address of the master NIC of the Kubernetes master node. If this field is not specified, the first IP address of the node where porter-manager is located will be used.
```

Currently, my worker node has 2 NICs. However, the automatically detected routerId is different from the NIC I want. Is there any way I can give this priority? (Example, as the interface name of the host)

**Comment by duanjiong** [comment]
If you don't specify it now, the router id is taken from node.status.Addresses, which is only used to indicate the router, not to connect to bgp, so you can just specify one.
