### ISSUE TITLE
Any improve

### ISSUE THREAD

**Issue by GeorgeGuo2018** [kubesphere/porter#50]
Suppose that there exist a service with service type LoadBalance,  and k8s maintained 2 Pods with according to deployment of  this service.
Suppose that Pod 1 was deployed on Node1 and Pod2 was deployed on Node2 on one moment.
The request for this service was equally divied to Node1 and Node2 with the help of porter.But once the request redirected to Node1, after the DNAT of kube-proxy, the request would still be change to the request Pod2. 
Can there do any improve to ensure,the request redirected to Node1 will surely transferred to the request for Pod1, and request received by Node2, will be transferred to the request for Pod2.

**Comment by magicsong** [comment]
This is user's decision.  user can specify the traffic policy of service to local. Then, the traffic will not route to other nodes. 
 you can check this [externalTrafficPolicy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#servicespec-v1-core)
> externalTrafficPolicy denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints. "Local" preserves the client source IP and avoids a second hop for LoadBalancer and Nodeport type services, but risks potentially imbalanced traffic spreading. "Cluster" obscures the client source IP and may cause a second hop to another node, but should have good overall load-spreading.

**Comment by GeorgeGuo2018** [comment]
Got it

**Comment by GeorgeGuo2018** [comment]
You can think about giving a best practice suggestion for users. 
for example, to get better load-balance effect, it is suggest to add podAntiAffinity in deployment using porter , Also user can try  externalTrafficPolicy option while define services thus to get better network performance.

**Comment by magicsong** [comment]
@GeorgeGuo2018 yes, you are right. But before more testing, we have no idea of best practise.
