### ISSUE TITLE
porter-manager pod的日志内有很多这样的日志

### ISSUE THREAD

**Issue by 53537** [kubesphere/porter#71]
E1114 09:49:45.091777       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:porter-system:default" cannot list resource "endpoints" in API group "" at the cluster scope

**Comment by magicsong** [comment]
这个RBAC没有安装好，删除了重新装一下试试呢

**Comment by 53537** [comment]
是从2.0.2升级到2.1出现的这些日志，且正式环境测试环境都有这种日志，正式环境可以正常使用，测试环境无法正常使用
