### ISSUE TITLE
期待增加loadBalancerIP和eip网段功能

### ISSUE THREAD

**Issue by 53537** [kubesphere/porter#73]
期待增加loadBalancerIP和eip网段功能，使用helm部署项目时loadBalancerIP对我们很重要

**Comment by FeynmanZhou** [comment]
@zheng1

**Comment by zheng1** [comment]
@k0ngk0ng I think you can implement loadBalancerIP as a first step.

May need to be modified here. https://github.com/kubesphere/porter/blob/master/controllers/lb/lb.go#L17
