### ISSUE TITLE
Suggest to support simple mode like layer 2

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/porter#75]
`The major advantage of the layer 2 mode is its universality: it will work on any ethernet network, with no special hardware required, not even fancy routers.`

@rayzhou2017 @calvinyv @zheng1 
I suggest layer 2 mode can be supported in Porter, to lower the threshold for testing, quick start and use. BGP mode is very appropriate for production but not that easy for new users. Furthermore, [MetalLB](https://metallb.universe.tf/concepts/layer2/) also supports layer 2, and there are [some users choose layer 2 mode](https://github.com/metallb/metallb/issues/5) as well.

**Comment by zheng1** [comment]
I tested it in layer 2 environment and it works well, but more tests are needed. 
Others can participate in the test if interested.

**Scenes: EIP/node/master/client should in the same subnet(e.g. 192.168.11.0/24).**

**Comment by FeynmanZhou** [comment]
@zheng1  Not sure what test cases are needed, it would be better that write a to-do list for test case thus we can participate in the test.

**Comment by zheng1** [comment]
@FeynmanZhou  https://kubesphere.com.cn/forum/d/759-porter
