### ISSUE TITLE
porter agent can be removed

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/porter#88]
Porter agent just add iptables rule to accept eip, but eip always be accepted.
And porter just need a controller to distribute various forward rules, such as bgp,arp, openflow etc. 
porter manager use the host network too, so we don't need agent any more.

**Comment by rayzhou2017** [comment]
Isn't the agent to write rules for the traffic back forth?

**Comment by duanjiong** [comment]
> Isn't the agent to write rules for the traffic back forth?

this done by kube-proxy
