### ISSUE TITLE
split bgp config

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/porter#89]
leave bgp portforward alone, and remove https://github.com/osrg/gobgp/internal/pkg files

**Comment by k0ngk0ng** [comment]
Does it mean that we'll use osrg/gobgp package directly, and delete the copies in /pkg/bgp ?

**Comment by duanjiong** [comment]
> Does it mean that we'll use osrg/gobgp package directly, and delete the copies in /pkg/bgp ?

Yes， refactor the porter config module

**Comment by duanjiong** [comment]
#98
