### ISSUE TITLE
BGP Additional Paths 

### ISSUE THREAD

**Issue by k0ngk0ng** [kubesphere/porter#90]
In BGP mode, the design of Porter and MetalLB are completely different.

**Porter:** 
The porter-manager will advertise the node IPs of all the Pods of a Service to the router.
Suppose we have a k8s cluster like this:
```
Roles          IP Address
master1        192.168.60.11
master2        192.168.60.12
master3        192.168.60.13
worker1        192.168.60.21
worker2        192.168.60.22
worker3        192.168.60.23
```
And we also have a deployment app, it's service EIP is 10.177.0.10 and replicas is 3, deployed on each workers. 

If we do not enable the BGP Additional Paths in router, maybe the BGP routing-table looks like this:
```
   Network                NextHop
*> 10.177.0.10/32         192.168.60.23
```
When the add-paths is enabled, the BGP routing-table is:
```
   Network                NextHop
*> 10.177.0.10/32         192.168.60.21
*                         192.168.60.22
*                         192.168.60.23
```

The reason is:
BGP routers and route reflectors (RRs) propagate only their best path over their sessions. The advertisement of a prefix replaces the previous announcement of that prefix (this behavior is known as an implicit withdraw). The implicit withdraw can achieve better scaling, but at the cost of path diversity. [[reference]](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-16/irg-xe-16-book/bgp-additional-paths.html)

**And not all routers support BGP Additional Paths. 
You cannot deploy HA LoadBalancer if your router does not have this feature.**

If you have 3 instances of the porter-manager on the cluster without add-paths enabled, then what happened? The BGP routing-table is unstable, maybe looks like this:
```
   Network                NextHop
*> 10.177.0.10/32         192.168.60.23
*                         192.168.60.23
*                         192.168.60.23
```
Disappointed right? But MetablLB does not have this problem.

**MetalLB:**
The BGP speakers are deployed as DaemonSets. Each speaker only advertise its own IP of node to router.

Whether or not additional-paths is enabled, the BGP routing-table is always like this:
```
   Network                NextHop
*> 10.177.0.10/32         192.168.60.21
*                         192.168.60.22
*                         192.168.60.23
```

So, when the router does not support BGP Additional-Paths, MetalLB is a better solution than Porter.

How can we change it?

**Comment by duanjiong** [comment]
That's indeed a problem.   I've also been working on BGP recently ,  I'll discuss it with you if there's any progress @k0ngk0ng  .   

What do you think about this @zheng1 ?

**Comment by zheng1** [comment]
This is a design based on our previous experience with public clouds, because in our environment add-paths are generally supported. At this point, it looks like we can support both, **distributed** or **centralized** to establish BGP connections to routers.
Distributed is implemented using DaemonSet. Centralized as before.

**Comment by duanjiong** [comment]
> This is a design based on our previous experience with public clouds, because in our environment add-paths are generally supported. At this point, it looks like we can support both, **distributed** or **centralized** to establish BGP connections to routers.
> Distributed is implemented using DaemonSet. Centralized as before.

I think It is not appropriate to maintain  both of them. If only a few routers do not support this feature, I think we can give this up.  If we use DaemonSet, then we are the same as Metallb.

**Comment by zheng1** [comment]
> > This is a design based on our previous experience with public clouds, because in our environment add-paths are generally supported. At this point, it looks like we can support both, **distributed** or **centralized** to establish BGP connections to routers.
> 
> > Distributed is implemented using DaemonSet. Centralized as before.
> 
> 
> 
> I think It is not appropriate to maintain  both of them. If only a few routers do not support this feature, I think we can give this up.  If we use DaemonSet, then we are the same as Metallb.

Modern switches can support this feature, at present, we do not need to modify the architecture in order to be compatible with legacy switches
