### ISSUE TITLE
User questionnaire design

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/porter#96]
We need to add a user survey in https://porterlb.io to gather the user requirements and user's switch, what questions should be included in this survey? 

Do not hesitate to leave your suggestions and ideas here.

**Comment by zheng1** [comment]
1. What is your role in the project?
2. Do you have permission to configure switches, routers?
3. Do you know the brand and model of the switch or router? If so, please write it down.
4. Are you familiar with the BGP protocol?
5. Are you familiar with the ARP protocol?
6. How do you implement the high availability of kubernetes' master in the production environment?
7. How many nodes do you use in the production environment?
8. How many nodes do you use in the development environment?

**Comment by FeynmanZhou** [comment]
Why we need Q6, Q7, Q8 for Porter?

**Comment by zheng1** [comment]
> Why we need Q6, Q7, Q8 for Porter? This questionnaire is for the roadmap and scenarios of Porter.

1. Consider supporting high master availability
2. Consider receiving data support for Porter deployment at large-scale
